name: phyloref_env
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - python=3.11  
  - snakemake=7.32.4
  - biopython=1.85
  - ete3=3.1.2
  - numpy
  - pandas
  - tqdm
  - requests
  - pyyaml
  - matplotlib-base
  - mafft
  - fasttree
  - graphviz
  - python-graphviz
  - pytest                 
  - pip                   
